import { prisma } from '@/lib/prisma'
import TemplatesPanel from './templates-panel'

export const dynamic = 'force-dynamic'

const templateCatalog = [
  {
    id: 'dis-klinikleri',
    name: 'Diş Klinikleri',
    sector: 'Diş Klinikleri',
    sprint: 1,
    colors: ['#0EA5E9', '#10B981', '#FFFFFF'],
    font: 'Outfit + DM Sans',
    description: 'Steril, ferah, modern klinik. Mavi güven tonu, randevu CTA.',
  },
  {
    id: 'veteriner-klinikleri',
    name: 'Veteriner Klinikleri',
    sector: 'Veteriner Klinikleri',
    sprint: 1,
    colors: ['#10B981', '#FFFDF7', '#92400E'],
    font: 'Nunito + Inter',
    description: 'Sıcak, güven verici, hayvan dostu. Yeşil/krem, yuvarlak şekiller.',
  },
  {
    id: 'optik-gozlukcu',
    name: 'Optik / Gözlükçü',
    sector: 'Optik / Gözlükçü',
    sprint: 1,
    colors: ['#1E40AF', '#D4AF37', '#FFFFFF'],
    font: 'Playfair Display + Source Sans',
    description: 'Premium, lüks optik mağaza. Lacivert/altın, serif başlıklar.',
  },
  {
    id: 'fizik-tedavi',
    name: 'Fizik Tedavi Merkezleri',
    sector: 'Fizik Tedavi Merkezleri',
    sprint: 1,
    colors: ['#0F766E', '#F8FFFE', '#14B8A6'],
    font: 'DM Sans + Lato',
    description: 'Sağlıklı, hareket, iyileşme. Teal gradyan, dalga şekilleri.',
  },
  {
    id: 'tip-merkezleri',
    name: 'Tıp Merkezleri',
    sector: 'Tıp Merkezleri',
    sprint: 1,
    colors: ['#1D4ED8', '#F8FAFC', '#0F172A'],
    font: 'Inter',
    description: 'Kurumsal, güvenilir, medikal. Profesyonel mavi, badge tarzı.',
  },
  {
    id: 'estetik-klinik',
    name: 'Estetik Klinik',
    sector: 'Estetik Klinikler',
    sprint: 1,
    colors: ['#F8F5F0', '#C9A96E', '#1C1917'],
    font: 'Cormorant Garamond + Jost',
    description: 'Lüks, premium, minimalist. Krem/altın, zarif serif tipografi.',
  },
  {
    id: 'psikolog-danisma',
    name: 'Psikolog / Danışman',
    sector: 'Psikologlar / Danışmanlar',
    sprint: 1,
    colors: ['#DDD6FE', '#6D28D9', '#FAF5FF'],
    font: 'Crimson Pro + Hind',
    description: 'Huzurlu, güvenli, gizli. Lavanta/mor, yumuşak yuvarlak formlar.',
  },
  {
    id: 'diyetisyen',
    name: 'Diyetisyen',
    sector: 'Diyetisyenler',
    sprint: 1,
    colors: ['#84CC16', '#FEFDF5', '#92400E'],
    font: 'Quicksand + Mulish',
    description: 'Sağlıklı, taze, motive edici. Canlı yeşil, enerji dolu.',
  },
  // ── Sprint 2: Sağlık & Klinik (2/3) + Güzellik (1/2) ──
  {
    id: 'isitme-merkezi',
    name: 'İşitme Merkezi',
    sector: 'İşitme Merkezleri',
    sprint: 2,
    colors: ['#0369A1', '#F97316', '#FFFFFF'],
    font: 'Poppins + Open Sans',
    description: 'Güven mavisi, teknoloji + bakım. Hero + cihaz teknoloji banner.',
  },
  {
    id: 'goz-merkezi',
    name: 'Göz Merkezi',
    sector: 'Göz Merkezleri',
    sprint: 2,
    colors: ['#0C4A6E', '#D4AF37', '#FFFFFF'],
    font: 'Raleway + Lato',
    description: 'Derin mavi + altın. Hexagonal hero mask, teknoloji kartı.',
  },
  {
    id: 'kuaforler',
    name: 'Kuaförler',
    sector: 'Kuaförler',
    sprint: 2,
    colors: ['#1C1917', '#F59E0B', '#FFFBEB'],
    font: 'Tenor Sans + Karla',
    description: 'Full-width hero BG, altın aksanlar, salon atmosferi.',
  },
  {
    id: 'berberler',
    name: 'Berberler',
    sector: 'Berberler',
    sprint: 2,
    colors: ['#292524', '#DC2626', '#FAFAF5'],
    font: 'Bebas Neue + Source Sans 3',
    description: 'Retro-modern, full-width hero BG, kırmızı aksanlar, erkeksi.',
  },
  {
    id: 'guzellik-spa',
    name: 'Güzellik / SPA',
    sector: 'Güzellik / SPA Merkezleri',
    sprint: 2,
    colors: ['#FDF2F8', '#BE185D', '#D4AF37'],
    font: 'Playfair Display + Jost',
    description: 'Lüks SPA, blob hero, ambiance banner, feminen.',
  },
  {
    id: 'cilt-bakim',
    name: 'Cilt Bakım Merkezi',
    sector: 'Cilt Bakım Merkezleri',
    sprint: 2,
    colors: ['#FEF9F0', '#92400E', '#16A34A'],
    font: 'Gilda Display + Hind Siliguri',
    description: 'Doğal, organik. Dikey hero kart, ürün sergileme kartı.',
  },
  {
    id: 'epilasyon',
    name: 'Epilasyon Merkezi',
    sector: 'Epilasyon Merkezleri',
    sprint: 2,
    colors: ['#FAFAF9', '#14B8A6', '#D4AF37'],
    font: 'Raleway + Nunito',
    description: 'Modern teal, geometrik çerçeveli hero, teknoloji kartı.',
  },
  {
    id: 'tirnak-studyosu',
    name: 'Tırnak Stüdyosu',
    sector: 'Tırnak Stüdyoları',
    sprint: 2,
    colors: ['#FF6B9D', '#1C1917', '#FFF1F5'],
    font: 'Montserrat + Nunito',
    description: 'Instagram-native, 3 slot galeri, eğimli pembe hero kartı.',
  },
  // ── Sprint 3: Güzellik (2/2) + Yeme-İçme ──
  {
    id: 'dovme-piercing',
    name: 'Dövme & Piercing',
    sector: 'Dövme & Piercing Stüdyoları',
    sprint: 3,
    colors: ['#0A0A0A', '#FF3D00', '#FFFFFF'],
    font: 'Barlow Condensed + Barlow',
    description: 'Underground, cesur, sanatsal. Dark portfolyo grid hero, neon glow.',
  },
  {
    id: 'restoranlar',
    name: 'Restoranlar',
    sector: 'Restoranlar',
    sprint: 3,
    colors: ['#1C1917', '#D97706', '#FAFAF5'],
    font: 'Cormorant Garamond + DM Sans',
    description: 'Sofistike fine dining. Full-width BG hero, menü kartı.',
  },
  {
    id: 'kafeler',
    name: 'Kafeler',
    sector: 'Kafeler',
    sprint: 3,
    colors: ['#78350F', '#FEF3C7', '#15803D'],
    font: 'Pacifico + Nunito',
    description: 'Sıcak kafe atmosferi. Diagonal clip hero, handwritten font.',
  },
  {
    id: 'pastaneler',
    name: 'Pastaneler',
    sector: 'Pastaneler',
    sprint: 3,
    colors: ['#FCE7F3', '#9D174D', '#D4AF37'],
    font: 'Dancing Script + Lato',
    description: 'El yapımı, artisanal. Masonry galeri hero, 3 slot.',
  },
  {
    id: 'firinlar',
    name: 'Fırınlar',
    sector: 'Fırınlar',
    sprint: 3,
    colors: ['#92400E', '#FDE68A', '#FFFBF0'],
    font: 'Lora + Source Sans 3',
    description: 'Geleneksel, sıcak. Panoramik banner hero, buğday tonları.',
  },
  {
    id: 'catering',
    name: 'Catering / Yemek Servisi',
    sector: 'Catering / Yemek Servisleri',
    sprint: 3,
    colors: ['#1E3A5F', '#F59E0B', '#F8FAFC'],
    font: 'Raleway + Open Sans',
    description: 'Kurumsal, profesyonel. 2-col grid hero, köşe aksanları.',
  },
  {
    id: 'kasaplar',
    name: 'Kasaplar',
    sector: 'Kasaplar',
    sprint: 3,
    colors: ['#7F1D1D', '#FDE68A', '#FFFBF5'],
    font: 'Oswald + Source Sans 3',
    description: 'Güçlü, güven. Diagonal split hero, kırmızı/krem.',
  },
  // ── Sprint 4: Gıda Perakende + Konaklama + Eğitim ──
  {
    id: 'manavlar',
    name: 'Manavlar',
    sector: 'Manavlar',
    sprint: 4,
    colors: ['#15803D', '#F97316', '#F0FFF4'],
    font: 'Nunito + Open Sans',
    description: 'Taze, organik. Circular produce grid hero, floating meyve badge\'leri.',
  },
  {
    id: 'kuruyemisciler',
    name: 'Kuruyemişçiler',
    sector: 'Kuruyemişçiler',
    sprint: 4,
    colors: ['#713F12', '#B8860B', '#FFFBF5'],
    font: 'Playfair Display + Lato',
    description: 'Sıcak, doğal. Shelf display hero, altın aksanlar.',
  },
  {
    id: 'sarkuteri',
    name: 'Şarküteri / Delikatessen',
    sector: 'Şarküteri / Delikatessen',
    sprint: 4,
    colors: ['#1C1917', '#F59E0B', '#DC2626'],
    font: 'Libre Baskerville + Karla',
    description: 'Gurme, premium. Dark floating card hero, amber glow.',
  },
  {
    id: 'su-bayileri',
    name: 'Su Bayileri',
    sector: 'Su Bayileri',
    sprint: 4,
    colors: ['#0EA5E9', '#BAE6FD', '#F0F9FF'],
    font: 'Poppins + Inter',
    description: 'Temiz, hijyen. Wave clip-path hero, water drop şekli.',
  },
  {
    id: 'oteller',
    name: 'Oteller',
    sector: 'Oteller',
    sprint: 4,
    colors: ['#0F172A', '#D4AF37', '#FFFBF0'],
    font: 'Cormorant Garamond + Raleway',
    description: 'Lüks konaklama. Full-width BG hero, altın overlay, komisyonsuz.',
  },
  {
    id: 'seyahat-acentesi',
    name: 'Seyahat Acentesi',
    sector: 'Seyahat Acenteleri',
    sprint: 4,
    colors: ['#0369A1', '#F97316', '#F8FAFC'],
    font: 'Rubik + DM Sans',
    description: 'Macera, keşif. Destination collage hero, posta pulu efektleri.',
  },
  {
    id: 'ozel-okullar',
    name: 'Özel Okullar / Kurslar',
    sector: 'Özel Okullar / Etüt Merkezleri',
    sprint: 4,
    colors: ['#1E40AF', '#FCD34D', '#F8FAFC'],
    font: 'Nunito + Hind',
    description: 'Modern eğitim. Geometric blocks hero, istatistik sayaçları.',
  },
]

export default async function TemplatesPage() {
  let pageStats: { template: string; count: number; views: number; chats: number; demos: number }[] = []
  try {
    const raw = await prisma.prospectPage.groupBy({
      by: ['template'] as const,
      _count: { _all: true },
      _sum: { viewCount: true, chatCount: true, demoCount: true },
    })
    pageStats = raw.map((r) => ({
      template: r.template,
      count: r._count._all,
      views: r._sum.viewCount ?? 0,
      chats: r._sum.chatCount ?? 0,
      demos: r._sum.demoCount ?? 0,
    }))
  } catch {
    // DB bağlantısı yoksa boş devam et
  }

  const statsMap = Object.fromEntries(pageStats.map((s) => [s.template, s]))

  return <TemplatesPanel catalog={templateCatalog} stats={statsMap} />
}
