import { prisma } from '@/lib/prisma'
import TemplatesPanel from './templates-panel'

export const dynamic = 'force-dynamic'

const templateCatalog = [
  {
    id: 'dis-klinikleri',
    name: 'Diş Klinikleri',
    sector: 'Diş Klinikleri',
    sprint: 1,
    colors: ['#0EA5E9', '#10B981', '#FFFFFF'],
    font: 'Outfit + DM Sans',
    description: 'Steril, ferah, modern klinik. Mavi güven tonu, randevu CTA.',
  },
  {
    id: 'veteriner-klinikleri',
    name: 'Veteriner Klinikleri',
    sector: 'Veteriner Klinikleri',
    sprint: 1,
    colors: ['#10B981', '#FFFDF7', '#92400E'],
    font: 'Nunito + Inter',
    description: 'Sıcak, güven verici, hayvan dostu. Yeşil/krem, yuvarlak şekiller.',
  },
  {
    id: 'optik-gozlukcu',
    name: 'Optik / Gözlükçü',
    sector: 'Optik / Gözlükçü',
    sprint: 1,
    colors: ['#1E40AF', '#D4AF37', '#FFFFFF'],
    font: 'Playfair Display + Source Sans',
    description: 'Premium, lüks optik mağaza. Lacivert/altın, serif başlıklar.',
  },
  {
    id: 'fizik-tedavi',
    name: 'Fizik Tedavi Merkezleri',
    sector: 'Fizik Tedavi Merkezleri',
    sprint: 1,
    colors: ['#0F766E', '#F8FFFE', '#14B8A6'],
    font: 'DM Sans + Lato',
    description: 'Sağlıklı, hareket, iyileşme. Teal gradyan, dalga şekilleri.',
  },
  {
    id: 'tip-merkezleri',
    name: 'Tıp Merkezleri',
    sector: 'Tıp Merkezleri',
    sprint: 1,
    colors: ['#1D4ED8', '#F8FAFC', '#0F172A'],
    font: 'Inter',
    description: 'Kurumsal, güvenilir, medikal. Profesyonel mavi, badge tarzı.',
  },
  {
    id: 'estetik-klinik',
    name: 'Estetik Klinik',
    sector: 'Estetik Klinikler',
    sprint: 1,
    colors: ['#F8F5F0', '#C9A96E', '#1C1917'],
    font: 'Cormorant Garamond + Jost',
    description: 'Lüks, premium, minimalist. Krem/altın, zarif serif tipografi.',
  },
  {
    id: 'psikolog-danisma',
    name: 'Psikolog / Danışman',
    sector: 'Psikologlar / Danışmanlar',
    sprint: 1,
    colors: ['#DDD6FE', '#6D28D9', '#FAF5FF'],
    font: 'Crimson Pro + Hind',
    description: 'Huzurlu, güvenli, gizli. Lavanta/mor, yumuşak yuvarlak formlar.',
  },
  {
    id: 'diyetisyen',
    name: 'Diyetisyen',
    sector: 'Diyetisyenler',
    sprint: 1,
    colors: ['#84CC16', '#FEFDF5', '#92400E'],
    font: 'Quicksand + Mulish',
    description: 'Sağlıklı, taze, motive edici. Canlı yeşil, enerji dolu.',
  },
  // ── Sprint 2: Sağlık & Klinik (2/3) + Güzellik (1/2) ──
  {
    id: 'isitme-merkezi',
    name: 'İşitme Merkezi',
    sector: 'İşitme Merkezleri',
    sprint: 2,
    colors: ['#0369A1', '#F97316', '#FFFFFF'],
    font: 'Poppins + Open Sans',
    description: 'Güven mavisi, teknoloji + bakım. Hero + cihaz teknoloji banner.',
  },
  {
    id: 'goz-merkezi',
    name: 'Göz Merkezi',
    sector: 'Göz Merkezleri',
    sprint: 2,
    colors: ['#0C4A6E', '#D4AF37', '#FFFFFF'],
    font: 'Raleway + Lato',
    description: 'Derin mavi + altın. Hexagonal hero mask, teknoloji kartı.',
  },
  {
    id: 'kuaforler',
    name: 'Kuaförler',
    sector: 'Kuaförler',
    sprint: 2,
    colors: ['#1C1917', '#F59E0B', '#FFFBEB'],
    font: 'Tenor Sans + Karla',
    description: 'Full-width hero BG, altın aksanlar, salon atmosferi.',
  },
  {
    id: 'berberler',
    name: 'Berberler',
    sector: 'Berberler',
    sprint: 2,
    colors: ['#292524', '#DC2626', '#FAFAF5'],
    font: 'Bebas Neue + Source Sans 3',
    description: 'Retro-modern, full-width hero BG, kırmızı aksanlar, erkeksi.',
  },
  {
    id: 'guzellik-spa',
    name: 'Güzellik / SPA',
    sector: 'Güzellik / SPA Merkezleri',
    sprint: 2,
    colors: ['#FDF2F8', '#BE185D', '#D4AF37'],
    font: 'Playfair Display + Jost',
    description: 'Lüks SPA, blob hero, ambiance banner, feminen.',
  },
  {
    id: 'cilt-bakim',
    name: 'Cilt Bakım Merkezi',
    sector: 'Cilt Bakım Merkezleri',
    sprint: 2,
    colors: ['#FEF9F0', '#92400E', '#16A34A'],
    font: 'Gilda Display + Hind Siliguri',
    description: 'Doğal, organik. Dikey hero kart, ürün sergileme kartı.',
  },
  {
    id: 'epilasyon',
    name: 'Epilasyon Merkezi',
    sector: 'Epilasyon Merkezleri',
    sprint: 2,
    colors: ['#FAFAF9', '#14B8A6', '#D4AF37'],
    font: 'Raleway + Nunito',
    description: 'Modern teal, geometrik çerçeveli hero, teknoloji kartı.',
  },
  {
    id: 'tirnak-studyosu',
    name: 'Tırnak Stüdyosu',
    sector: 'Tırnak Stüdyoları',
    sprint: 2,
    colors: ['#FF6B9D', '#1C1917', '#FFF1F5'],
    font: 'Montserrat + Nunito',
    description: 'Instagram-native, 3 slot galeri, eğimli pembe hero kartı.',
  },
  // ── Sprint 3: Güzellik (2/2) + Yeme-İçme ──
  {
    id: 'dovme-piercing',
    name: 'Dövme & Piercing',
    sector: 'Dövme & Piercing Stüdyoları',
    sprint: 3,
    colors: ['#0A0A0A', '#FF3D00', '#FFFFFF'],
    font: 'Barlow Condensed + Barlow',
    description: 'Underground, cesur, sanatsal. Dark portfolyo grid hero, neon glow.',
  },
  {
    id: 'restoranlar',
    name: 'Restoranlar',
    sector: 'Restoranlar',
    sprint: 3,
    colors: ['#1C1917', '#D97706', '#FAFAF5'],
    font: 'Cormorant Garamond + DM Sans',
    description: 'Sofistike fine dining. Full-width BG hero, menü kartı.',
  },
  {
    id: 'kafeler',
    name: 'Kafeler',
    sector: 'Kafeler',
    sprint: 3,
    colors: ['#78350F', '#FEF3C7', '#15803D'],
    font: 'Pacifico + Nunito',
    description: 'Sıcak kafe atmosferi. Diagonal clip hero, handwritten font.',
  },
  {
    id: 'pastaneler',
    name: 'Pastaneler',
    sector: 'Pastaneler',
    sprint: 3,
    colors: ['#FCE7F3', '#9D174D', '#D4AF37'],
    font: 'Dancing Script + Lato',
    description: 'El yapımı, artisanal. Masonry galeri hero, 3 slot.',
  },
  {
    id: 'firinlar',
    name: 'Fırınlar',
    sector: 'Fırınlar',
    sprint: 3,
    colors: ['#92400E', '#FDE68A', '#FFFBF0'],
    font: 'Lora + Source Sans 3',
    description: 'Geleneksel, sıcak. Panoramik banner hero, buğday tonları.',
  },
  {
    id: 'catering',
    name: 'Catering / Yemek Servisi',
    sector: 'Catering / Yemek Servisleri',
    sprint: 3,
    colors: ['#1E3A5F', '#F59E0B', '#F8FAFC'],
    font: 'Raleway + Open Sans',
    description: 'Kurumsal, profesyonel. 2-col grid hero, köşe aksanları.',
  },
  {
    id: 'kasaplar',
    name: 'Kasaplar',
    sector: 'Kasaplar',
    sprint: 3,
    colors: ['#7F1D1D', '#FDE68A', '#FFFBF5'],
    font: 'Oswald + Source Sans 3',
    description: 'Güçlü, güven. Diagonal split hero, kırmızı/krem.',
  },
  // ── Sprint 4: Gıda Perakende + Konaklama + Eğitim ──
  {
    id: 'manavlar',
    name: 'Manavlar',
    sector: 'Manavlar',
    sprint: 4,
    colors: ['#15803D', '#F97316', '#F0FFF4'],
    font: 'Nunito + Open Sans',
    description: 'Taze, organik. Circular produce grid hero, floating meyve badge\'leri.',
  },
  {
    id: 'kuruyemisciler',
    name: 'Kuruyemişçiler',
    sector: 'Kuruyemişçiler',
    sprint: 4,
    colors: ['#713F12', '#B8860B', '#FFFBF5'],
    font: 'Playfair Display + Lato',
    description: 'Sıcak, doğal. Shelf display hero, altın aksanlar.',
  },
  {
    id: 'sarkuteri',
    name: 'Şarküteri / Delikatessen',
    sector: 'Şarküteri / Delikatessen',
    sprint: 4,
    colors: ['#1C1917', '#F59E0B', '#DC2626'],
    font: 'Libre Baskerville + Karla',
    description: 'Gurme, premium. Dark floating card hero, amber glow.',
  },
  {
    id: 'su-bayileri',
    name: 'Su Bayileri',
    sector: 'Su Bayileri',
    sprint: 4,
    colors: ['#0EA5E9', '#BAE6FD', '#F0F9FF'],
    font: 'Poppins + Inter',
    description: 'Temiz, hijyen. Wave clip-path hero, water drop şekli.',
  },
  {
    id: 'oteller',
    name: 'Oteller',
    sector: 'Oteller',
    sprint: 4,
    colors: ['#0F172A', '#D4AF37', '#FFFBF0'],
    font: 'Cormorant Garamond + Raleway',
    description: 'Lüks konaklama. Full-width BG hero, altın overlay, komisyonsuz.',
  },
  {
    id: 'seyahat-acentesi',
    name: 'Seyahat Acentesi',
    sector: 'Seyahat Acenteleri',
    sprint: 4,
    colors: ['#0369A1', '#F97316', '#F8FAFC'],
    font: 'Rubik + DM Sans',
    description: 'Macera, keşif. Destination collage hero, posta pulu efektleri.',
  },
  {
    id: 'ozel-okullar',
    name: 'Özel Okullar / Kurslar',
    sector: 'Özel Okullar / Etüt Merkezleri',
    sprint: 4,
    colors: ['#1E40AF', '#FCD34D', '#F8FAFC'],
    font: 'Nunito + Hind',
    description: 'Modern eğitim. Geometric blocks hero, istatistik sayaçları.',
  },
  // ── Sprint 5: Eğitim (devamı) + Spor + Otomotiv (1/2) ──
  {
    id: 'kresler',
    name: 'Kreşler',
    sector: 'Kreşler',
    sprint: 5,
    colors: ['#FEF08A', '#86EFAC', '#FCA5A5'],
    font: 'Nunito + Quicksand',
    description: 'Renkli, çocuk dostu. Rainbow blocks hero, floating oyuncak badge\'leri.',
  },
  {
    id: 'muzik-kurslari',
    name: 'Müzik Kursları',
    sector: 'Müzik Kursları',
    sprint: 5,
    colors: ['#1C1917', '#F59E0B', '#DC2626'],
    font: 'Abril Fatface + Lato',
    description: 'Dark sahne, altın nota aksanı. Spotlight hero, sanatsal atmosfer.',
  },
  {
    id: 'spor-salonlari',
    name: 'Spor Salonları',
    sector: 'Spor Salonları',
    sprint: 5,
    colors: ['#0A0A0A', '#F97316', '#A3A3A3'],
    font: 'Barlow Condensed + Barlow',
    description: 'Güçlü, dinamik. Diagonal split clip-path hero, turuncu şerit.',
  },
  {
    id: 'pilates-yoga',
    name: 'Pilates / Yoga',
    sector: 'Pilates / Yoga Stüdyoları',
    sprint: 5,
    colors: ['#FAFAF9', '#A8A29E', '#84CC16'],
    font: 'Josefin Sans + Lato',
    description: 'Minimal, huzurlu. Zen circle hero, nefes halkaları, yeşil aksanlar.',
  },
  {
    id: 'oto-galeri',
    name: 'Oto Galeri',
    sector: 'Oto Galeri',
    sprint: 5,
    colors: ['#0A0A0A', '#DC2626', '#C0C0C0'],
    font: 'Rajdhani + Roboto',
    description: 'Premium showroom. Full-width BG hero, spotlight overlay, kırmızı aksanlar.',
  },
  {
    id: 'oto-servis',
    name: 'Oto Servis',
    sector: 'Oto Mekanik / Servisler',
    sprint: 5,
    colors: ['#1E293B', '#F97316', '#94A3B8'],
    font: 'Rajdhani + Source Sans 3',
    description: 'Endüstriyel, güvenilir. Grid hero, tool badge strip, turuncu köşe aksanları.',
  },
  {
    id: 'lastikci',
    name: 'Lastikçi',
    sector: 'Lastik / Rot Balans',
    sprint: 5,
    colors: ['#171717', '#EF4444', '#EAB308'],
    font: 'Bebas Neue + Open Sans',
    description: 'Hızlı, güçlü. Tire-track pattern hero, speed lines, kırmızı+sarı aksanlar.',
  },
  // ── Sprint 6: Otomotiv (2/2) + İnşaat (1/3) ──
  {
    id: 'oto-egzoz',
    name: 'Oto Egzoz',
    sector: 'Oto Egzoz',
    sprint: 6,
    colors: ['#1C1917', '#DC2626', '#C0C0C0'],
    font: 'Rajdhani + Source Sans 3',
    description: 'Teknik, performans. Chrome mesh hero, muayene garantisi badge.',
  },
  {
    id: 'oto-kaporta',
    name: 'Oto Kaporta & Boya',
    sector: 'Oto Kaporta',
    sprint: 6,
    colors: ['#0F172A', '#FFFFFF', '#94A3B8'],
    font: 'Rajdhani + Lato',
    description: 'Mükemmeliyetçi. Before/After diagonal split hero, metalik gradient.',
  },
  {
    id: 'oto-cam',
    name: 'Oto Cam',
    sector: 'Oto Cam',
    sprint: 6,
    colors: ['#0C4A6E', '#BAE6FD', '#FFFFFF'],
    font: 'Inter + Lato',
    description: 'Temiz, cam gibi. Frosted glass card hero, cam yansıma efekti.',
  },
  {
    id: 'motosiklet-servisi',
    name: 'Motosiklet Servisi',
    sector: 'Motosiklet Servisleri',
    sprint: 6,
    colors: ['#0A0A0A', '#F97316', '#808080'],
    font: 'Barlow Condensed + Barlow',
    description: 'Özgürlük, yol ruhu. Road perspective hero, chrome circle frame.',
  },
  {
    id: 'insaat-firmalari',
    name: 'İnşaat Firmaları',
    sector: 'Müteahhitler',
    sprint: 6,
    colors: ['#1E3A5F', '#D97706', '#94A3B8'],
    font: 'Oswald + Source Sans 3',
    description: 'Güçlü, kurumsal. Blueprint grid hero, construction badge strip.',
  },
  {
    id: 'mimarlik-ofisleri',
    name: 'Mimarlık / Tadilat',
    sector: 'İç Mimarlar / Dekorasyon',
    sprint: 6,
    colors: ['#FAFAF9', '#171717', '#D4AF37'],
    font: 'Cormorant Garamond + Jost',
    description: 'Minimal, şık. Golden ratio asymmetric hero, altın portfolio frame.',
  },
  {
    id: 'tadilat-dekorasyon',
    name: 'PVC / Doğrama',
    sector: 'PVC / Cam Balkon',
    sprint: 6,
    colors: ['#F8FAFC', '#0F172A', '#64748B'],
    font: 'Raleway + Open Sans',
    description: 'Modern bina. Window frame mockup hero, cam yansıma, ısı yalıtım.',
  },
  // ── Sprint 7: İnşaat (2/3) ──
  {
    id: 'isi-yalitim',
    name: 'Isı Yalıtım / Mantolama',
    sector: 'Isı Yalıtım / Mantolama',
    sprint: 7,
    colors: ['#78350F', '#FDE68A', '#FFFFFF'],
    font: 'Oswald + Lato',
    description: 'Enerji tasarrufu. Thermal layer hero, gauge badge, sıcak tonlar.',
  },
  {
    id: 'dis-cephe',
    name: 'Dış Cephe Kaplama',
    sector: 'Dış Cephe Kaplama',
    sprint: 7,
    colors: ['#374151', '#F59E0B', '#FFFFFF'],
    font: 'Oswald + Lato',
    description: 'Profesyonel, güçlü. Facade grid hero, malzeme kart strip, amber aksanlar.',
  },
  {
    id: 'cati-sistemleri',
    name: 'Çatı Sistemleri',
    sector: 'Çatı & İzolasyon',
    sprint: 7,
    colors: ['#1E293B', '#DC2626', '#94A3B8'],
    font: 'Oswald + Source Sans 3',
    description: 'Güçlü, dayanıklı. Roof cross-section SVG hero, garanti shield badge.',
  },
  {
    id: 'fayans-seramik',
    name: 'Fayans / Seramik',
    sector: 'Fayans / Seramik',
    sprint: 7,
    colors: ['#F8F5F2', '#92400E', '#A8A29E'],
    font: 'Playfair Display + Karla',
    description: 'Ev dekorasyonu. Mosaic tile pattern hero, toprak paleti, serif tipografi.',
  },
  {
    id: 'asma-tavan',
    name: 'Asma Tavan / Alçıpan',
    sector: 'Asma Tavan / Alçıpan',
    sprint: 7,
    colors: ['#F1F5F9', '#0F172A', '#94A3B8'],
    font: 'Inter + Lato',
    description: 'Modern, temiz. Ceiling perspective lines hero, silver metalik çerçeve.',
  },
  {
    id: 'boya-badana',
    name: 'Boya Badana',
    sector: 'Boyacılar',
    sprint: 7,
    colors: ['#FEF9F0', '#1C1917', '#EAB308'],
    font: 'Nunito + Open Sans',
    description: 'Renkli, temiz. Rainbow paint drip hero, renk çemberi dekor.',
  },
  {
    id: 'elektrikci',
    name: 'Elektrikçi',
    sector: 'Elektrikçiler',
    sprint: 7,
    colors: ['#1C1917', '#FCD34D', '#DC2626'],
    font: 'Barlow Condensed + Barlow',
    description: 'Güçlü, acil. Lightning bolt SVG + circuit pattern hero, 7/24 strip.',
  },
  {
    id: 'tesisatci',
    name: 'Tesisatçı',
    sector: 'Tesisatçılar',
    sprint: 7,
    colors: ['#1E3A5F', '#0EA5E9', '#94A3B8'],
    font: 'Poppins + Source Sans 3',
    description: 'Su, güvenilir. Water pipe network hero, droplet frame, 24 saat strip.',
  },
  {
    id: 'mermer-granit',
    name: 'Mermer & Granit',
    sector: 'Mermer / Granit',
    sprint: 8,
    colors: ['#0A0A0A', '#D4AF37', '#F8F5F2'],
    font: 'Cormorant Garamond + Raleway',
    description: 'Lüks, premium. Marble vein SVG + gold ornamental frame hero.',
  },
  {
    id: 'parke-zemin',
    name: 'Parke & Zemin Döşeme',
    sector: 'Parke / Zemin Kaplama',
    sprint: 8,
    colors: ['#92400E', '#FDE68A', '#FBF8F4'],
    font: 'Lora + Source Sans 3',
    description: 'Sıcak, doğal. Wood grain SVG + ahşap plank frame hero.',
  },
  {
    id: 'dosemeci',
    name: 'Döşemeci / Koltuk Tamircisi',
    sector: 'Döşemeciler',
    sprint: 8,
    colors: ['#713F12', '#FDE68A', '#FBF7F0'],
    font: 'Playfair Display + Karla',
    description: 'El işçiliği, geleneksel. Leather stitch SVG + before/after hero.',
  },
  {
    id: 'marangoz',
    name: 'Marangoz / Ahşap Atölyesi',
    sector: 'Marangozlar',
    sprint: 8,
    colors: ['#78350F', '#FDE68A', '#FBF8F2'],
    font: 'Libre Baskerville + Lato',
    description: 'Zanaat, sıcak. Chisel mark SVG + wood workshop frame hero.',
  },
  {
    id: 'cadir-tente',
    name: 'Çadır & Tente İmalatı',
    sector: 'Çadır / Tente İmalatı',
    sprint: 8,
    colors: ['#166534', '#FDE68A', '#F8FAF8'],
    font: 'Oswald + Open Sans',
    description: 'Dayanıklı, dış mekan. Canopy wave SVG + striped top border hero.',
  },
  {
    id: 'branda',
    name: 'Branda İmalatı',
    sector: 'Branda İmalatı',
    sprint: 8,
    colors: ['#1E3A5F', '#F59E0B', '#F1F5F9'],
    font: 'Oswald + Source Sans 3',
    description: 'Endüstriyel, B2B. Industrial grid SVG + B2B strip hero.',
  },
  {
    id: 'kaynak-demir',
    name: 'Kaynak & Demir Atölyesi',
    sector: 'Demiriciler / Ferforje',
    sprint: 8,
    colors: ['#0A0A0A', '#F97316', '#171717'],
    font: 'Barlow Condensed + Barlow',
    description: 'Güçlü, ateş-demir. Weld sparks SVG + molten glow frame hero.',
  },
  {
    id: 'bobinaj',
    name: 'Bobinaj',
    sector: 'Bobinajcılar',
    sprint: 8,
    colors: ['#1E293B', '#F59E0B', '#F1F5F9'],
    font: 'Oswald + Source Sans 3',
    description: 'Teknik, B2B. Copper coil SVG + ring decorations hero.',
  },
  // ── Sprint 9: Atölye (2/2) + Hizmet & Perakende ──
  {
    id: 'matbaalar',
    name: 'Matbaalar',
    sector: 'Matbaacılar',
    sprint: 9,
    colors: ['#1C1917', '#DC2626', '#FAFAF8'],
    font: 'Oswald + DM Sans',
    description: 'CMYK baskı estetiği. Full-width merkezi hero, CMYK gradient bantlar, büyük tipografi watermark.',
  },
  {
    id: 'ambalaj',
    name: 'Ambalaj İmalat',
    sector: 'Ambalaj / Paketleme',
    sprint: 9,
    colors: ['#374151', '#F59E0B', '#F9FAFB'],
    font: 'Oswald + Source Sans 3',
    description: 'Diagonal split hero (çapraz bölünme), skewed görsel çerçeve, asimetrik 3:2 grid.',
  },
  {
    id: 'plastik-imalat',
    name: 'Plastik İmalat',
    sector: 'Plastik İmalatı',
    sprint: 9,
    colors: ['#0369A1', '#BAE6FD', '#FFFFFF'],
    font: 'Raleway + Source Sans 3',
    description: 'Merkezi text-first hero, 3-sütun ürün kart grid, beyaz CTA mavi bg.',
  },
  {
    id: 'terzi',
    name: 'Terzi / Moda Atölyesi',
    sector: 'Terzi / Konfeksiyoncular',
    sprint: 9,
    colors: ['#4C1D95', '#D4AF37', '#FDF8F0'],
    font: 'Cormorant Garamond + Lato',
    description: 'Butik, zarif. Dikey stack + dairesel görsel, altın iplik çizgi süslemeleri.',
  },
  {
    id: 'tabela-reklam',
    name: 'Tabela & Reklam',
    sector: 'Tabelacılar / Reklam',
    sprint: 9,
    colors: ['#0A0A0A', '#F97316', '#111111'],
    font: 'Barlow Condensed + Barlow',
    description: 'Neon glow tam ekran hero, ızgara overlay, parlayan tipografi, karanlık atmosfer.',
  },
  {
    id: 'hukuk-burosu',
    name: 'Hukuk Bürosu',
    sector: 'Avukatlar',
    sprint: 9,
    colors: ['#1E3A5F', '#D4AF37', '#FFFFFF'],
    font: 'Playfair Display + Source Serif 4',
    description: 'Prestij, güven. Ters asimetrik hero (sol görsel, sağ metin), altın köşe aksanları.',
  },
  {
    id: 'muhasebe',
    name: 'Muhasebe / Mali Müşavirlik',
    sector: 'Muhasebeciler / SMMM',
    sprint: 9,
    colors: ['#166534', '#1E3A5F', '#FFFFFF'],
    font: 'Raleway + Open Sans',
    description: 'Minimal tipografi-only hero (görsel yok), istatistik kartları, defter çizgi arka planı.',
  },
  {
    id: 'sigorta',
    name: 'Sigorta Acentesi',
    sector: 'Sigorta Acenteleri',
    sprint: 9,
    colors: ['#0F766E', '#99F6E4', '#FFFFFF'],
    font: 'Poppins + Hind',
    description: 'Üst-alt dikey bölünme, dalga SVG geçişi, kalkan overlay, sigorta branş kartları.',
  },
  // ── Sprint 10: Perakende + Teknik Servis (1/2) ──
  {
    id: 'emlak-ofisi',
    name: 'Emlak Ofisi',
    sector: 'Emlakçılar',
    sprint: 10,
    colors: ['#0F172A', '#D4AF37', '#FFFFFF'],
    font: 'Cormorant Garamond + Raleway',
    description: 'Diagonal split clip-path hero, sol koyu metin sağ çapraz mülk görseli, altın prestij.',
  },
  {
    id: 'mobilya',
    name: 'Mobilya Mağazası',
    sector: 'Mobilya Mağazaları',
    sprint: 10,
    colors: ['#FAFAF9', '#292524', '#8B6914'],
    font: 'Cormorant Garamond + Karla',
    description: 'Editorial magazine hero, tam görsel + örtüşen beyaz kart, dergi kapağı estetiği.',
  },
  {
    id: 'elektronik',
    name: 'Elektronik Mağazası',
    sector: 'Elektronik Mağazaları',
    sprint: 10,
    colors: ['#0F172A', '#3B82F6', '#FFFFFF'],
    font: 'Poppins + Inter',
    description: 'Floating tech cards hero, circuit grid arka plan, neon mavi glow, ürün kategorisi.',
  },
  {
    id: 'kirtasiye',
    name: 'Kırtasiye',
    sector: 'Kırtasiyeler',
    sprint: 10,
    colors: ['#FEF3C7', '#1E40AF', '#DC2626'],
    font: 'Nunito + Open Sans',
    description: 'Playful angled color blocks hero, renkli dönen bloklar, not defteri nokta deseni.',
  },
  {
    id: 'pet-shop',
    name: 'Pet Shop',
    sector: 'Pet Shop',
    sprint: 10,
    colors: ['#ECFDF5', '#F59E0B', '#78350F'],
    font: 'Nunito + Quicksand',
    description: 'Organic blob mask hero, yumuşak organik şekil içinde görsel, pati izi süslemeler.',
  },
  {
    id: 'cicekci',
    name: 'Çiçekçi',
    sector: 'Çiçekçiler',
    sprint: 10,
    colors: ['#FDF2F8', '#BE185D', '#15803D'],
    font: 'Playfair Display + Nunito',
    description: 'Botanical frame hero, SVG çiçek köşe bordürleri, romantik merkezi text, italic başlık.',
  },
  {
    id: 'kuyumcu',
    name: 'Kuyumcu',
    sector: 'Kuyumcular',
    sprint: 10,
    colors: ['#0A0A0A', '#D4AF37', '#1C1917'],
    font: 'Cormorant Garamond + Jost',
    description: 'Cinematic letterbox hero, ultra-geniş yatay şerit görsel, altın border, lüks toz efekti.',
  },
  {
    id: 'tekstil-giyim',
    name: 'Tekstil / Giyim',
    sector: 'Tekstil / Giyim Mağazası',
    sprint: 10,
    colors: ['#1C1917', '#F59E0B', '#FDF8F0'],
    font: 'Tenor Sans + Karla',
    description: 'Runway lookbook hero, tam ekran bg görsel + dikey merkezi text stack, moda editoryal.',
  },
  // ── Sprint 11: Teknik Servis (2/2) + Diğer Hizmetler ──
  {
    id: 'spor-malzemeleri',
    name: 'Spor Malzemeleri',
    sector: 'Spor Malzemeleri Mağazası',
    sprint: 11,
    colors: ['#1C1917', '#EA580C', '#FFF7ED'],
    font: 'Barlow Condensed + Barlow',
    description: 'Dynamic slash SVG overlay hero, köşegen enerji çizgileri, spor mağaza estetiği.',
  },
  {
    id: 'klima-servisi',
    name: 'Klima Servisi',
    sector: 'Klima Servisi',
    sprint: 11,
    colors: ['#0EA5E9', '#BAE6FD', '#FFFFFF'],
    font: 'Poppins + Inter',
    description: 'Frosted glass split hero, backdrop-blur glassmorphism kart + buz kristal dekorasyon.',
  },
  {
    id: 'kombi-servisi',
    name: 'Kombi Servisi',
    sector: 'Kombi Servisi',
    sprint: 11,
    colors: ['#1E3A5F', '#F97316', '#FFFFFF'],
    font: 'Oswald + Source Sans 3',
    description: 'Emergency banner hero, kırmızı pulse üst bant + marka grid + stat kartlar.',
  },
  {
    id: 'beyaz-esya',
    name: 'Beyaz Eşya',
    sector: 'Beyaz Eşya Tamircisi',
    sprint: 11,
    colors: ['#0F172A', '#DC2626', '#F8FAFC'],
    font: 'Poppins + Inter',
    description: 'Horizontal appliance strip hero, yatay ikon bandı + dot grid temiz estetik.',
  },
  {
    id: 'asansor',
    name: 'Asansör',
    sector: 'Asansör Bakım',
    sprint: 11,
    colors: ['#1E293B', '#C0C0C0', '#DC2626'],
    font: 'Rajdhani + Source Sans 3',
    description: 'Vertical shaft perspective hero, dikey kuyu çizgileri + kat numaraları + metalik estetiği.',
  },
  {
    id: 'jenerator',
    name: 'Jeneratör',
    sector: 'Jeneratör Servisi',
    sprint: 11,
    colors: ['#0A0A0A', '#FCD34D', '#111111'],
    font: 'Oswald + Source Sans 3',
    description: 'Power pulse grid hero, endüstriyel grid overlay + sarı enerji pulse + kVA kartlar.',
  },
  {
    id: 'guvenlik-sistemleri',
    name: 'Güvenlik Sistemleri',
    sector: 'Güvenlik Sistemleri',
    sprint: 11,
    colors: ['#0D1117', '#DC2626', '#FFFFFF'],
    font: 'Rajdhani + Source Sans 3',
    description: 'Surveillance monitor grid hero, 2x2 CCTV ekran + matrix overlay + HUD köşe çerçeveleri.',
  },
  {
    id: 'cilingir',
    name: 'Çilingir',
    sector: 'Çilingir',
    sprint: 11,
    colors: ['#1C1917', '#F59E0B', '#78716C'],
    font: 'Barlow Condensed + Barlow',
    description: 'Bold emergency centered hero, devasa "15 dk" tipografi + amber flash çizgileri.',
  },
  // ── Sprint 12: Diğer Hizmetler ──
  {
    id: 'su-aritma',
    name: 'Su Arıtma',
    sector: 'Su Arıtma Servisi',
    sprint: 12,
    colors: ['#0EA5E9', '#F0F9FF', '#FFFFFF'],
    font: 'Poppins + Inter',
    description: 'Concentric water ripple hero, iç içe daireler + ücretsiz su testi kartı.',
  },
  {
    id: 'fotograf-studyosu',
    name: 'Fotoğraf Stüdyosu',
    sector: 'Fotoğraf Stüdyoları',
    sprint: 12,
    colors: ['#0A0A0A', '#D4AF37', '#FFFFFF'],
    font: 'Cormorant Garamond + Raleway',
    description: 'Camera aperture SVG hero, diyafram çizgileri + ışık hüzmesi + sanatsal.',
  },
  {
    id: 'temizlik',
    name: 'Temizlik Şirketi',
    sector: 'Temizlik Şirketleri',
    sprint: 12,
    colors: ['#ECFDF5', '#0F766E', '#FFFFFF'],
    font: 'Poppins + Nunito',
    description: 'Sparkling diagonal wipe hero, köşegen temizlik çizgisi + sparkle efekti.',
  },
  {
    id: 'kuru-temizleme',
    name: 'Kuru Temizleme',
    sector: 'Kuru Temizleme',
    sprint: 12,
    colors: ['#E0F2FE', '#0369A1', '#FFFFFF'],
    font: 'Nunito + Open Sans',
    description: 'Hanger rack perspective hero, askı kancaları + kaçış noktası çizgileri.',
  },
  {
    id: 'hali-yikama',
    name: 'Halı Yıkama',
    sector: 'Halı Yıkama',
    sprint: 12,
    colors: ['#78350F', '#FDE68A', '#FFFBEB'],
    font: 'Lora + Source Sans 3',
    description: 'Before/after vertical split hero, dikey bölünme + dönüşüm estetiği.',
  },
  {
    id: 'nakliyat',
    name: 'Nakliyat',
    sector: 'Nakliyat Firmaları',
    sprint: 12,
    colors: ['#0F172A', '#F97316', '#64748B'],
    font: 'Oswald + Source Sans 3',
    description: 'Road path + arrows hero, yol çizgisi + yön okları + hız blur efekti.',
  },
  {
    id: 'organizasyon',
    name: 'Organizasyon',
    sector: 'Organizasyon Şirketleri',
    sprint: 12,
    colors: ['#0A0A0A', '#D4AF37', '#FFFFFF'],
    font: 'Cormorant Garamond + Jost',
    description: 'Theatrical spotlight hero, sahne spot ışıkları + perde çizgileri + altın elegans.',
  },
  // ── Sprint 13 ──
  {
    id: 'ozel-poliklinik',
    name: 'Özel Poliklinik',
    sector: 'Özel Poliklinik',
    sprint: 13,
    colors: ['#ECFEFF', '#0891B2', '#FFFFFF'],
    font: 'Plus Jakarta Sans + Inter',
    description: 'ECG heartbeat hero, tıbbi haç + nabız çizgisi, teal medikal ton.',
  },
  {
    id: 'dil-kurslari',
    name: 'Dil Kursları',
    sector: 'Dil Kursları',
    sprint: 13,
    colors: ['#1E1B4B', '#A78BFA', '#FFFFFF'],
    font: 'Space Grotesk + DM Sans',
    description: 'Floating speech bubbles hero, Hello/Hola/Bonjour, koyu mor + violet.',
  },
  {
    id: 'etut-merkezleri',
    name: 'Etüt Merkezleri',
    sector: 'Etüt Merkezleri',
    sprint: 13,
    colors: ['#FFFBEB', '#D97706', '#1C1917'],
    font: 'Merriweather + Source Sans 3',
    description: 'Open book pages fan hero, kalem aksanı, sıcak krem + amber.',
  },
  {
    id: 'surucu-kurslari',
    name: 'Sürücü Kursları',
    sector: 'Sürücü Kursları',
    sprint: 13,
    colors: ['#1C1917', '#22C55E', '#EF4444'],
    font: 'Rajdhani + Inter',
    description: 'Road vanishing point hero, trafik ışığı glow noktaları, asfalt koyu + yeşil.',
  },
  {
    id: 'oto-yikama',
    name: 'Oto Yıkama',
    sector: 'Oto Yıkama',
    sprint: 13,
    colors: ['#0C4A6E', '#38BDF8', '#FFFFFF'],
    font: 'Exo 2 + Nunito',
    description: 'Water wave splash hero, köpük bubble circles, derin mavi + açık mavi.',
  },
  {
    id: 'oto-elektrik',
    name: 'Oto Elektrik',
    sector: 'Oto Elektrik',
    sprint: 13,
    colors: ['#111827', '#FBBF24', '#FFFFFF'],
    font: 'Chakra Petch + Inter',
    description: 'Circuit traces + lightning hero, devre yolları + yıldırım, koyu + elektrik sarısı.',
  },
  // ── Sprint 14 ──
  {
    id: 'oto-yedek-parca',
    name: 'Oto Yedek Parça',
    sector: 'Oto Yedek Parça',
    sprint: 14,
    colors: ['#1F2937', '#F97316', '#FFFFFF'],
    font: 'Barlow + Source Sans 3',
    description: 'Interlocking gears hero, birbirine kenetlenen dişliler, çelik gri + turuncu.',
  },
  {
    id: 'oto-aksesuar',
    name: 'Oto Aksesuar',
    sector: 'Oto Aksesuar',
    sprint: 14,
    colors: ['#0F0F0F', '#8B5CF6', '#FFFFFF'],
    font: 'Outfit + DM Sans',
    description: 'Neon car silhouette hero, neon glow çizgiler + blur circles, siyah + neon mor.',
  },
  {
    id: 'pvc-dograma',
    name: 'PVC Doğrama',
    sector: 'PVC Doğrama',
    sprint: 14,
    colors: ['#F8FAFC', '#2563EB', '#FFFFFF'],
    font: 'Outfit + Inter',
    description: 'Window frame + light rays hero, pencere çerçevesi + ışık huzmeleri, açık + mavi.',
  },
  {
    id: 'aluminyum-dograma',
    name: 'Alüminyum Doğrama',
    sector: 'Alüminyum Doğrama',
    sprint: 14,
    colors: ['#F1F5F9', '#0284C7', '#94A3B8'],
    font: 'Archivo + Inter',
    description: 'Brushed metal grid hero, fırçalanmış metal profil ızgara, gümüş gri + mavi.',
  },
  {
    id: 'cam-balkon',
    name: 'Cam Balkon',
    sector: 'Cam Balkon',
    sprint: 14,
    colors: ['#F0F9FF', '#0EA5E9', '#FFFFFF'],
    font: 'Quicksand + Nunito Sans',
    description: 'Glass panels + sky reflection hero, cam paneller + gökyüzü yansıması, açık + cerulean.',
  },
  {
    id: 'prefabrik-yapi',
    name: 'Prefabrik Yapı',
    sector: 'Prefabrik Yapı',
    sprint: 14,
    colors: ['#18181B', '#F59E0B', '#FFFFFF'],
    font: 'Saira + Work Sans',
    description: 'Stacking blocks hero, üst üste yığılan modüler bloklar + vinç, koyu + amber.',
  },
]

export default async function TemplatesPage() {
  let pageStats: { template: string; count: number; views: number; chats: number; demos: number }[] = []
  try {
    const raw = await prisma.prospectPage.groupBy({
      by: ['template'] as const,
      _count: { _all: true },
      _sum: { viewCount: true, chatCount: true, demoCount: true },
    })
    pageStats = raw.map((r) => ({
      template: r.template,
      count: r._count._all,
      views: r._sum.viewCount ?? 0,
      chats: r._sum.chatCount ?? 0,
      demos: r._sum.demoCount ?? 0,
    }))
  } catch {
    // DB bağlantısı yoksa boş devam et
  }

  const statsMap = Object.fromEntries(pageStats.map((s) => [s.template, s]))

  return <TemplatesPanel catalog={templateCatalog} stats={statsMap} />
}
