// Realistic Turkish seed data for empty DB states
// Used as fallback when DB has no records

export const seedClients = [
  {
    id: "seed-1",
    name: "Mehmet Sarıgül",
    company: "Sarıgül Otomotiv",
    email: "mehmet@sariguloto.com",
    phone: "0532 XXX XX XX",
    sector: "Otomotiv",
    status: "ACTIVE" as const,
    totalRevenue: 24000,
    notes: null,
    createdAt: new Date("2025-09-15"),
    updatedAt: new Date("2026-03-20"),
  },
  {
    id: "seed-2",
    name: "Ayşe Demir",
    company: "Güzellik Merkezi Lina",
    email: "ayse@linaspa.com",
    phone: "0544 XXX XX XX",
    sector: "Güzellik / SPA",
    status: "ACTIVE" as const,
    totalRevenue: 18500,
    notes: null,
    createdAt: new Date("2025-11-02"),
    updatedAt: new Date("2026-03-25"),
  },
  {
    id: "seed-3",
    name: "Ali Yılmaz",
    company: "Anatolian Spa Hotel",
    email: "info@anatolianspa.com",
    phone: "0242 XXX XX XX",
    sector: "Otelcilik",
    status: "MAINTENANCE" as const,
    totalRevenue: 45000,
    notes: "Bakım paketi aktif",
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2026-03-01"),
  },
  {
    id: "seed-4",
    name: "Hasan Koray",
    company: "Koray Hukuk Bürosu",
    email: "hasan@korayhukuk.com",
    phone: "0532 XXX XX XX",
    sector: "Hukuk",
    status: "POTENTIAL" as const,
    totalRevenue: 0,
    notes: "Teklif gönderildi, yanıt bekleniyor",
    createdAt: new Date("2026-03-10"),
    updatedAt: new Date("2026-03-23"),
  },
  {
    id: "seed-5",
    name: "Fatma Kaya",
    company: "restocafe.com",
    email: "fatma@restocafe.com",
    phone: "0555 XXX XX XX",
    sector: "Yeme-İçme",
    status: "MAINTENANCE" as const,
    totalRevenue: 32000,
    notes: "SSL 7 gün sonra doluyor",
    createdAt: new Date("2025-04-20"),
    updatedAt: new Date("2026-03-27"),
  },
];

export const seedProjects = [
  {
    id: "seed-p1",
    title: "DisSağlık Dental Web Sitesi",
    clientName: "DisSağlık Dental",
    type: "WEBSITE" as const,
    status: "DEVELOPMENT" as const,
    budget: 22000,
    progress: 65,
    techStack: ["Next.js 15", "Tailwind", "Prisma"],
    startDate: new Date("2026-02-15"),
    deadline: new Date("2026-04-01"),
  },
  {
    id: "seed-p2",
    title: "FitZone Spor Mobil App",
    clientName: "FitZone Spor",
    type: "MOBILE_APP" as const,
    status: "DESIGN" as const,
    budget: 65000,
    progress: 30,
    techStack: ["Kotlin", "Jetpack Compose", "Room"],
    startDate: new Date("2026-03-01"),
    deadline: new Date("2026-05-15"),
  },
  {
    id: "seed-p3",
    title: "Lezzet Durağı E-Ticaret",
    clientName: "Lezzet Durağı",
    type: "ECOMMERCE" as const,
    status: "TESTING" as const,
    budget: 35000,
    progress: 90,
    techStack: ["Next.js", "İyzico", "PostgreSQL"],
    startDate: new Date("2026-01-10"),
    deadline: new Date("2026-03-30"),
  },
];

export const seedLeads = [
  {
    id: "seed-l1",
    name: "Güneş Diş Kliniği",
    company: "Güneş Diş Kliniği",
    address: "Muratpaşa, Antalya",
    source: "MAPS_SCRAPER" as const,
    status: "COLD" as const,
    budget: "₺12-18K",
    sector: "Sağlık",
    type: "Web sitesi",
  },
  {
    id: "seed-l2",
    name: "Koray Hukuk Bürosu",
    company: "Koray Hukuk Bürosu",
    address: "Konyaaltı, Antalya",
    source: "SITE_FORM" as const,
    status: "MEETING" as const,
    budget: "₺20-25K",
    sector: "Hukuk",
    type: "Kurumsal web",
  },
  {
    id: "seed-l3",
    name: "Akdeniz Spor Kompleksi",
    company: "Akdeniz Spor Kompleksi",
    address: "Kepez, Antalya",
    source: "LINKEDIN" as const,
    status: "QUOTED" as const,
    budget: "₺60-80K",
    sector: "Spor",
    type: "Mobil uygulama",
  },
];

export const seedAlerts = [
  {
    type: "payment" as const,
    dot: "red" as const,
    title: "Güzellik Merkezi — Ödeme 5 gün gecikmeli",
    meta: "Proje: Web Sitesi · ₺4.500 bekliyor",
    action: "WA",
    actionType: "primary" as const,
  },
  {
    type: "ssl" as const,
    dot: "red" as const,
    title: "restocafe.com — SSL 7 gün içinde doluyor",
    meta: "Bakım müşterisi · Otomatik yenile",
    action: "Yenile",
    actionType: "default" as const,
  },
  {
    type: "quote" as const,
    dot: "amber" as const,
    title: "Sarıgül Otomotiv — Teklif 4 gündür yanıtsız",
    meta: "₺18.000 · Gönderildi: 23 Mar",
    action: "Takip et",
    actionType: "primary" as const,
  },
  {
    type: "maintenance" as const,
    dot: "green" as const,
    title: "Anatolian Spa — Bu ay bakım yenileme",
    meta: "₺2.000/ay · Nisan yenilemesi",
    action: "Teklif hazırla",
    actionType: "default" as const,
  },
];

export const seedPayments = [
  {
    id: "seed-pay1",
    projectTitle: "Güzellik Merkezi Web",
    amount: 4500,
    dueDate: new Date("2026-03-22"),
    status: "OVERDUE" as const,
    type: "MILESTONE" as const,
    invoiceNo: "INV-2026-011",
  },
  {
    id: "seed-pay2",
    projectTitle: "DisSağlık Dental",
    amount: 8800,
    dueDate: new Date("2026-04-01"),
    status: "PENDING" as const,
    type: "MILESTONE" as const,
    invoiceNo: "INV-2026-012",
  },
  {
    id: "seed-pay3",
    projectTitle: "Lezzet Durağı E-Ticaret",
    amount: 10500,
    dueDate: new Date("2026-03-30"),
    status: "PENDING" as const,
    type: "FINAL" as const,
    invoiceNo: "INV-2026-013",
  },
  {
    id: "seed-pay4",
    projectTitle: "Sarıgül Otomotiv Web",
    amount: 7200,
    dueDate: new Date("2026-02-15"),
    status: "PAID" as const,
    type: "DEPOSIT" as const,
    invoiceNo: "INV-2026-008",
  },
];
